name: Build HA addon stable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Add on version'
        required: true
        type: string

concurrency:
  group: ha-addon-build
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update README and set version in config.json
        run: |
          rsync -a --delete wmbusmeters-ha-addon-edge/ wmbusmeters-ha-addon/ --exclude CHANGELOG.md
          sed -i 's/\[edge\] //g; s/-edge//g' wmbusmeters-ha-addon/config.json
          sed -i "s|\s\{4,\}\"version\".*|    \"version\": \"${{ inputs.version }}\"\,|g" wmbusmeters-ha-addon/config.json
          sed -i "1s|^|## ${{ inputs.version }} \n- Updated to version [${{ inputs.version }}](https://github.com/wmbusmeters/wmbusmeters/blob/master/CHANGES)\n|" wmbusmeters-ha-addon/CHANGELOG.md

      - uses: actions/upload-artifact@v3
        with:
          name: ha-addon_artifact-${{ inputs.version }}
          path: ${{ github.workspace }}
          retention-days: 1

  build:
    needs: prepare
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ["wmbusmeters"]
        arch: ["amd64", "armv7", "aarch64"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ha-addon_artifact-${{ inputs.version }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build ${{ matrix.addon }} ${{ matrix.arch }} HA add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target wmbusmeters-ha-addon \
            --version ${{ inputs.version }}

  update-repo:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ha-addon_artifact-${{ inputs.version }}

      - name: Push changed files back to repo
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Auto Push - update ha-addon config and changelog for ${{ inputs.version }} - [no ci]"
